### ISSUE TITLE
quick question: old code?

### ISSUE THREAD

**Issue by jorbor** [forest2087/inventoryEventSource#2]
Hi Forest, was taking a look at your code and just wondering -- is there a lot of old stuff here? Things copied from an old project?

Thanks! Jordan

**Comment by forest2087** [comment]
No it's a fresh copy of laravel 5.2

**Comment by forest2087** [comment]
You can take a look at their repo here if you are interested: 
https://github.com/laravel/laravel

Thanks
Cheers
